# Generated by Django 5.1.3 on 2024-11-29 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_lunuser_avatar_lunuser_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lunuser",
            name="work_ends_at",
        ),
        migrations.RemoveField(
            model_name="lunuser",
            name="work_starts_at",
        ),
        migrations.CreateModel(
            name="RieltorWorkShedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workdays_starts_at", models.TimeField(blank=True, null=True)),
                ("workdays_ends_at", models.TimeField(blank=True, null=True)),
                ("weekend_starts_at", models.TimeField(blank=True, null=True)),
                ("workend_ends_at", models.TimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_shedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
