# Generated by Django 5.1.3 on 2024-11-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_lunuser_work_ends_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rieltorworkshedule",
            options={
                "verbose_name": "Work Shedule",
                "verbose_name_plural": "Work Shedules",
            },
        ),
        migrations.AlterModelTable(
            name="rieltorworkshedule",
            table="work_shedule",
        ),
    ]
