# Generated by Django 5.1.3 on 2024-11-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=256)),
                (
                    "project_type",
                    models.IntegerField(
                        choices=[
                            (1, "1-room"),
                            (2, "2-room"),
                            (3, "3-room"),
                            (4, "4-room"),
                            (5, "5-room"),
                            (6, "Comorer"),
                            (7, "Commerce"),
                            (8, "Cottege"),
                            (9, "Duplex"),
                            (10, "Townhouse"),
                        ]
                    ),
                ),
                (
                    "cottage_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "project_state",
                    models.IntegerField(choices=[(1, "builded"), (2, "build")]),
                ),
                ("min_price_per_sqrm", models.IntegerField(blank=True, null=True)),
                ("max_price_per_sqrm", models.IntegerField(blank=True, null=True)),
                ("solded", models.BooleanField(default=False)),
                ("min_area", models.FloatField(blank=True, null=True)),
                ("cottage_area", models.FloatField(blank=True, null=True)),
                ("max_area", models.FloatField(blank=True, null=True)),
                ("bedrooms_count", models.IntegerField(blank=True, null=True)),
                ("floors_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("company_name", models.CharField(max_length=128)),
                ("company_web", models.URLField(max_length=512)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
