# Generated by Django 5.1.9 on 2025-05-20 20:00

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewBuildings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("bio", django_ckeditor_5.fields.CKEditor5Field()),
                ("location", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=256)),
                (
                    "metro_station",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("company_name", models.CharField(max_length=128)),
                ("company_web", models.URLField(max_length=512)),
                (
                    "apartament_classes",
                    models.CharField(
                        choices=[
                            ("Econom", "Econom"),
                            ("Comfort", "Comfort"),
                            ("Buisnes", "Buisnes"),
                            ("Luxury", "Luxury"),
                        ]
                    ),
                ),
                ("houses_count", models.IntegerField(blank=True, null=True)),
                ("floors_variables", models.CharField(null=True)),
                (
                    "construction_tec",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("walls", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "walls_insulation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "project_heating",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ceiling_height", models.FloatField(null=True)),
                ("apartament_count", models.IntegerField(null=True)),
                (
                    "housing_condition",
                    models.CharField(
                        choices=[
                            ("With renovation", "With renovation"),
                            ("Without renovation", "Without renovation"),
                            (
                                "With renovation, Without renovation",
                                "With renovation, Without renovation",
                            ),
                        ]
                    ),
                ),
                ("parking", models.CharField(blank=True, max_length=100, null=True)),
                ("parking_places", models.IntegerField(null=True)),
                (
                    "backup_power_supply",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("shelter", models.CharField(blank=True, max_length=100, null=True)),
                ("first_apartamen_floor", models.IntegerField(blank=True, null=True)),
                ("last_apartamen_floor", models.IntegerField(blank=True, null=True)),
                (
                    "company_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="companies_logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rieltor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "New Building",
                "verbose_name_plural": "New Buildings",
                "db_table": "new_buildings",
            },
        ),
        migrations.CreateModel(
            name="NewBuildingsPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_project/"
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="newbuilding.newbuildings",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Building Photo",
                "verbose_name_plural": "New Buildings Photos",
                "db_table": "new_buildings_photos",
            },
        ),
        migrations.CreateModel(
            name="NewBuildingsProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apartament_type",
                    models.CharField(
                        choices=[
                            ("1-room", "1-room"),
                            ("2-room", "2-room"),
                            ("3-room", "3-room"),
                            ("4-room", "4-room"),
                            ("5-room", "5-room"),
                        ]
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("Builded", "Builded"), ("Build", "Build")]
                    ),
                ),
                ("price_per_sqrm", models.IntegerField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("solded", models.BooleanField(default=False)),
                ("apartamen_floor", models.CharField(blank=True, null=True)),
                ("last_apartamen_floor", models.IntegerField(blank=True, null=True)),
                ("apartamen_number", models.CharField(blank=True, null=True)),
                ("final_build_date", models.DateField(blank=True, null=True)),
                (
                    "aprtament_bedrooms_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rieltor_offer",
                        to="newbuilding.newbuildings",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Building Project",
                "verbose_name_plural": "New Buildings Projects",
                "db_table": "new_buildings_projects",
            },
        ),
    ]
