# Generated by Django 5.1.10 on 2025-07-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newbuildingsprojects",
            old_name="apartamen_floor",
            new_name="apartament_floor",
        ),
        migrations.RenameField(
            model_name="newbuildingsprojects",
            old_name="apartamen_number",
            new_name="apartament_number",
        ),
        migrations.RenameField(
            model_name="newbuildingsprojects",
            old_name="last_apartamen_floor",
            new_name="last_apartament_floor",
        ),
        migrations.AlterField(
            model_name="newbuildings",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="newbuildingsprojects",
            name="apartament_type",
            field=models.CharField(
                choices=[
                    ("1-room", "1-room"),
                    ("2-rooms", "2-rooms"),
                    ("3-rooms", "3-rooms"),
                    ("4-rooms", "4-rooms"),
                    ("5-rooms", "5-rooms"),
                ]
            ),
        ),
    ]
