# Generated by Django 5.1.3 on 2024-11-25 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyprojects",
            options={
                "verbose_name": "Company Project",
                "verbose_name_plural": "Companies Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="newbuilding",
            options={
                "verbose_name": "New Building",
                "verbose_name_plural": "New Buildings",
            },
        ),
        migrations.AlterField(
            model_name="companyprojects",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rieltor_offer",
                to="newbuilding.newbuilding",
            ),
        ),
        migrations.AlterModelTable(
            name="companyprojects",
            table="companies_projects",
        ),
        migrations.AlterModelTable(
            name="newbuilding",
            table="new_buildings",
        ),
    ]
