# Generated by Django 5.1.10 on 2025-07-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "newbuilding",
            "0002_rename_apartamen_floor_newbuildingsprojects_apartament_floor_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newbuildings",
            name="first_apartamen_floor",
        ),
        migrations.RemoveField(
            model_name="newbuildings",
            name="last_apartamen_floor",
        ),
    ]
