# Generated by Django 5.1.10 on 2025-07-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0003_remove_newbuildings_first_apartamen_floor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="last_apartament_floor",
        ),
    ]
