# Generated by Django 5.1.3 on 2024-11-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0003_alter_companyprojects_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyprojects",
            old_name="city",
            new_name="location",
        ),
        migrations.AddField(
            model_name="companyprojects",
            name="station",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
