# Generated by Django 5.1.3 on 2024-11-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0004_rename_city_companyprojects_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprojects",
            name="project_state",
            field=models.CharField(choices=[(1, "builded"), (2, "build")]),
        ),
        migrations.AlterField(
            model_name="companyprojects",
            name="project_type",
            field=models.CharField(
                choices=[
                    (1, "1-room"),
                    (2, "2-room"),
                    (3, "3-room"),
                    (4, "4-room"),
                    (5, "5-room"),
                    (6, "Comorer"),
                    (7, "Commerce"),
                    (8, "Cottege"),
                    (9, "Duplex"),
                    (10, "Townhouse"),
                ]
            ),
        ),
    ]
