# Generated by Django 5.1.3 on 2024-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0005_alter_companyprojects_project_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprojects",
            name="project_state",
            field=models.CharField(
                choices=[("builded", "builded"), ("builded", "build")]
            ),
        ),
        migrations.AlterField(
            model_name="companyprojects",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("1-room", "1-room"),
                    ("2-room", "2-room"),
                    ("3-room", "3-room"),
                    ("4-room", "4-room"),
                    ("5-room", "5-room"),
                    ("Comorer", "Comorer"),
                    ("Commerce", "Commerce"),
                    ("Cottege", "Cottege"),
                    ("Duplex", "Duplex"),
                    ("Townhouse", "Townhouse"),
                ]
            ),
        ),
    ]
