# Generated by Django 5.1.3 on 2024-11-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newbuilding",
            "0007_rename_cottage_area_companyprojects_townhouse_area_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprojects",
            name="townhouse_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
