# Generated by Django 5.1.3 on 2024-11-27 11:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0009_rename_newbuilding_newbuildings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewBuildingsProjecrts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=256)),
                (
                    "metro_station",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "apartament_type",
                    models.CharField(
                        choices=[
                            ("1-room", "1-room"),
                            ("2-room", "2-room"),
                            ("3-room", "3-room"),
                            ("4-room", "4-room"),
                            ("5-room", "5-room"),
                        ]
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("Builded", "Builded"), ("Builded", "Build")]
                    ),
                ),
                ("min_price_per_sqrm", models.IntegerField(blank=True, null=True)),
                ("max_price_per_sqrm", models.IntegerField(blank=True, null=True)),
                ("solded", models.BooleanField(default=False)),
                ("min_area", models.FloatField(blank=True, null=True)),
                ("max_area", models.FloatField(blank=True, null=True)),
                (
                    "apartament_classes",
                    models.CharField(
                        choices=[
                            ("Econom", "Econom"),
                            ("Comfort", "Comfort"),
                            ("Buisnes", "Buisnes"),
                            ("Luxury", "Luxury"),
                        ]
                    ),
                ),
                ("houses_count", models.IntegerField()),
                (
                    "floors_vars",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                ("construction_tec", models.CharField(max_length=50)),
                ("walls", models.CharField(max_length=50)),
                ("walls_insulation", models.CharField(max_length=100)),
                ("project_heating", models.CharField(max_length=100)),
                ("ceiling_height", models.FloatField()),
                ("apartament_count", models.IntegerField()),
                ("water_supply", models.CharField(max_length=100)),
                ("sewerage", models.CharField(max_length=50)),
                (
                    "housing_condition",
                    models.CharField(
                        choices=[
                            ("With renovation", "With renovation"),
                            ("Without renovation", "Without renovation"),
                            (
                                "With renovation, Without renovation",
                                "With renovation, Without renovation",
                            ),
                        ]
                    ),
                ),
                ("parking", models.CharField(max_length=100)),
                ("bacup_power_supply", models.CharField(max_length=100)),
                ("shelter", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rieltor_offer",
                        to="newbuilding.newbuildings",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NewBuildingsCompaniesProjects",
        ),
    ]
