# Generated by Django 5.1.3 on 2024-11-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0010_newbuildingsprojecrts_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newbuildingsprojecrts",
            options={
                "verbose_name": "New Building Project",
                "verbose_name_plural": "New Buildings Projects",
            },
        ),
        migrations.AlterModelTable(
            name="newbuildingsprojecrts",
            table="new_buildings_projects",
        ),
    ]
