# Generated by Django 5.1.3 on 2024-11-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0012_alter_newbuildingsprojecrts_apartament_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newbuildingsprojecrts",
            name="apartamen_floor",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildingsprojecrts",
            name="aprtament_bedrooms_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildingsprojecrts",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildingsprojecrts",
            name="final_build_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildingsprojecrts",
            name="first_apartamen_floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildingsprojecrts",
            name="last_apartamen_floor",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
