# Generated by Django 5.1.3 on 2024-11-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0013_newbuildingsprojecrts_apartamen_floor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newbuildingsprojecrts",
            name="sewerage",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojecrts",
            name="water_supply",
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="bio",
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newbuildingsprojecrts",
            name="floors_vars",
            field=models.CharField(blank=True, null=True),
        ),
    ]
