# Generated by Django 5.1.3 on 2024-11-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0015_newbuildingsprojecrts_fixed_price_per_sqrm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newbuildingsprojecrts",
            name="area",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojecrts",
            name="fixed_price_per_sqrm",
        ),
        migrations.AddField(
            model_name="newbuildingsprojecrts",
            name="parking_places",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
