# Generated by Django 5.1.3 on 2024-11-27 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0016_remove_newbuildingsprojecrts_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newbuildings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
