# Generated by Django 5.1.3 on 2024-11-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0022_remove_newbuildings_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newbuildings",
            name="company_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="companies_logos/"
            ),
        ),
    ]
