# Generated by Django 5.1.3 on 2024-11-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0026_remove_newbuildingsprojects_district_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="apartament_classes",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="apartament_count",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="bacup_power_supply",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="ceiling_height",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="construction_tec",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="first_apartamen_floor",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="floors_vars",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="houses_count",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="housing_condition",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="parking",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="parking_places",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="project_heating",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="walls",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="walls_insulation",
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="apartament_classes",
            field=models.CharField(
                choices=[
                    ("Econom", "Econom"),
                    ("Comfort", "Comfort"),
                    ("Buisnes", "Buisnes"),
                    ("Luxury", "Luxury"),
                ],
                default=str,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="apartament_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="bacup_power_supply",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="ceiling_height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="construction_tec",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="first_apartamen_floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="floors_variables",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="houses_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="housing_condition",
            field=models.CharField(
                choices=[
                    ("With renovation", "With renovation"),
                    ("Without renovation", "Without renovation"),
                    (
                        "With renovation, Without renovation",
                        "With renovation, Without renovation",
                    ),
                ],
                default=str,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="last_apartamen_floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="parking",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="parking_places",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="project_heating",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="shelter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="walls",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="newbuildings",
            name="walls_insulation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="newbuildingsprojects",
            name="apartamen_number",
            field=models.CharField(blank=True, null=True),
        ),
    ]
