# Generated by Django 5.1.3 on 2024-11-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0027_remove_newbuildingsprojects_apartament_classes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="max_area",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="max_price_per_sqrm",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="min_area",
        ),
        migrations.RemoveField(
            model_name="newbuildingsprojects",
            name="min_price_per_sqrm",
        ),
        migrations.AddField(
            model_name="newbuildingsprojects",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbuildingsprojects",
            name="price_per_sqrm",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
