# Generated by Django 5.1.3 on 2024-12-02 18:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "newbuilding",
            "0029_rename_bacup_power_supply_newbuildings_backup_power_supply",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="newbuildings",
            name="bio",
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1024),
        ),
    ]
