# Generated by Django 5.1.3 on 2024-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0030_alter_newbuildings_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newbuildings",
            name="apartament_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="newbuildings",
            name="ceiling_height",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="newbuildings",
            name="floors_variables",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="newbuildings",
            name="parking_places",
            field=models.IntegerField(null=True),
        ),
    ]
