# Generated by Django 5.1.3 on 2024-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newbuilding", "0031_alter_newbuildings_apartament_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newbuildingsprojects",
            name="state",
            field=models.CharField(
                choices=[("Builded", "Builded"), ("Build", "Build")]
            ),
        ),
    ]
