# Generated by Django 5.1.9 on 2025-05-20 20:00

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Properties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("bio", django_ckeditor_5.fields.CKEditor5Field(max_length=1024)),
                ("location", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=256)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("bedrooms_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rieltor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "db_table": "property",
            },
        ),
        migrations.CreateModel(
            name="Houses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house_state",
                    models.CharField(
                        choices=[("builded", "builded"), ("build", "build")]
                    ),
                ),
                ("floors_count", models.IntegerField(null=True)),
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house",
                        to="properties.properties",
                    ),
                ),
            ],
            options={
                "verbose_name": "House",
                "verbose_name_plural": "Houses",
                "db_table": "houses",
            },
        ),
        migrations.CreateModel(
            name="Apartaments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apartament_type",
                    models.CharField(
                        choices=[
                            ("1-room", "1-room"),
                            ("2-room", "2-room"),
                            ("3-room", "3-room"),
                            ("4-room", "4-room"),
                            ("5-room", "5-room"),
                        ]
                    ),
                ),
                ("station", models.CharField(blank=True, max_length=50, null=True)),
                ("floor", models.IntegerField()),
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartament",
                        to="properties.properties",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartament",
                "verbose_name_plural": "Apartaments",
                "db_table": "apartaments",
            },
        ),
        migrations.CreateModel(
            name="PropertyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="property/"),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_property",
                        to="properties.properties",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Photo",
                "verbose_name_plural": "Properties Photos",
                "db_table": "property_photos",
            },
        ),
    ]
