# Generated by Django 5.1.10 on 2025-07-25 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorite", "0001_initial"),
        ("newbuilding", "0003_remove_newbuildings_first_apartamen_floor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newbuildingsprojectsfavorite",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_count",
                to="newbuilding.newbuildings",
            ),
        ),
        migrations.AlterField(
            model_name="newbuildingsprojectsfavorite",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_count",
                to="newbuilding.newbuildingsprojects",
            ),
        ),
    ]
