# Generated by Django 5.1.3 on 2024-12-18 09:37

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartaments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "bio",
                    ckeditor_uploader.fields.RichTextUploadingField(max_length=1024),
                ),
                (
                    "apartament_type",
                    models.CharField(
                        choices=[
                            ("1-room", "1-room"),
                            ("2-room", "2-room"),
                            ("3-room", "3-room"),
                            ("4-room", "4-room"),
                            ("5-room", "5-room"),
                        ]
                    ),
                ),
                ("location", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=256)),
                ("station", models.CharField(blank=True, max_length=50, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("bedrooms_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rieltor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartament",
                "verbose_name_plural": "Apartaments",
                "db_table": "apartaments",
            },
        ),
        migrations.CreateModel(
            name="Houses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "bio",
                    ckeditor_uploader.fields.RichTextUploadingField(max_length=1024),
                ),
                (
                    "house_state",
                    models.CharField(
                        choices=[("builded", "builded"), ("build", "build")]
                    ),
                ),
                ("location", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=256)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("bedrooms_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rieltor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "House",
                "verbose_name_plural": "Houses",
                "db_table": "houses",
            },
        ),
    ]
