# Generated by Django 5.1.3 on 2024-12-18 12:02

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartaments",
            name="address",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="area",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="bedrooms_count",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="location",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="price",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="rieltor",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="title",
        ),
        migrations.RemoveField(
            model_name="apartaments",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="address",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="area",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="bedrooms_count",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="location",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="price",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="rieltor",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="title",
        ),
        migrations.RemoveField(
            model_name="houses",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="houses",
            name="floors_count",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Properties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "bio",
                    ckeditor_uploader.fields.RichTextUploadingField(max_length=1024),
                ),
                ("location", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=256)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("bedrooms_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rieltor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "db_table": "property",
            },
        ),
        migrations.AddField(
            model_name="apartaments",
            name="offer",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartament",
                to="property.properties",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="houses",
            name="offer",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house",
                to="property.properties",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PropertyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="property/"),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_property",
                        to="property.properties",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Photo",
                "verbose_name_plural": "Properties Photos",
                "db_table": "property_photos",
            },
        ),
    ]
