# Generated by Django 5.1.3 on 2024-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "property",
            "0002_remove_apartaments_address_remove_apartaments_area_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apartaments",
            name="floor",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
